// <auto-generated />
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250821025641_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electronics",
                            Url = "electronics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Travel",
                            Url = "travel"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Description = "Advanced A17 Pro chip, titanium design, 6.7-inch display, triple-camera system.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-blue-titanium",
                            Name = "Flagship Smartphone",
                            Price = 1499.99m,
                            Title = "Apple iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "Industry-leading noise cancelling, 30h battery, crystal-clear sound.",
                            ImageUrl = "https://m.media-amazon.com/images/I/61+FXSxKsBL._AC_SX679_.jpg",
                            Name = "Noise Cancelling Headphones",
                            Price = 399.00m,
                            Title = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Quantum Matrix Technology Pro, HDR10+, Dolby Atmos, ultra-slim design.",
                            ImageUrl = "https://image.samsung.com/is/image/samsung/p6pim/levant/qn75qn900cfmxzn/gallery/levant-qled-qn900c-477953-477953-477953-477953.png",
                            Name = "Smart TV",
                            Price = 4999.99m,
                            Title = "Samsung Neo QLED 8K Smart TV 75”"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "12th Gen Intel Core i7, RTX 3050 Ti, 15.6-inch 4K OLED, premium build.",
                            ImageUrl = "https://i.dell.com/sites/csimages/App-Merchandizing_Images/all/xps-15-9520-laptop-pdp-gallery-504x350.jpg",
                            Name = "Professional Laptop",
                            Price = 2199.00m,
                            Title = "Dell XPS 15 Laptop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Illustrated hardcover edition: The Fellowship, Two Towers, Return of the King.",
                            ImageUrl = "https://m.media-amazon.com/images/I/81t2CVWEsUL._AC_UF1000,1000_QL80_.jpg",
                            Name = "Fantasy Novel Collection",
                            Price = 89.99m,
                            Title = "The Lord of the Rings Trilogy Book Set"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Maps, trekking routes, cultural insights, survival tips for Himalayas.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006_%28square%29.jpg/330px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006_%28square%29.jpg",
                            Name = "Travel Guide",
                            Price = 54.50m,
                            Title = "Everest Base Camp Trekking Guidebook"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
